### ISSUE TITLE
Lazy initialization of drone instances and Parallel execution

### ISSUE THREAD

**Issue by punitbisht** [arquillian/arquillian-extension-drone#102]
##### Lazy Initialization of Drone in Parallel execution

Flag ``` -Darquillian.drone.skip.creation=true ``` will skip initialization of the Drone instances as per the change in Version 2.2.0. 
Now imagine we have 220 test cases and each test case update this flag in @Before method. This change is global and will be applicable for all the tests whic will execute after current one.

Solution to this problem would be , reset the flag in @After method. 

But what about the scenario where we are executing multiple tests in parallel using maven

```

<forkCount>5</forkCount>
<reuseForks>false</reuseForks>

```

**Comment by MatousJobanek** [comment]
Hi,

yeah, for parallel testing it is not the best solution. I didn't consider this use case. 
I'm not sure if there is another (easier) way of solving this than using lazy loading - initialize Drone when it is called for the first time. Maybe some kind of `@Rule` could solve it, but it is not the optimal solution either. 

I'll try to draft something next week and I'll let you know if there is some progress.
If you have any other idea or you are willing to help with it, I'll be more thankful.

**Comment by punitbisht** [comment]
@MatousJobanek I am wondering if cukespace team can add some solution on there side may be . I have reported this issue there . Will share If I hear anything form them

**Comment by punitbisht** [comment]
@MatousJobanek  we have fixed this issue with some fixes on our implementation , Please refer my latest comments on the above link . I guess you can close the issue if you want .
