### ISSUE TITLE
Issue with dependency

### ISSUE THREAD

**Issue by konjp** [arquillian/arquillian-extension-drone#126]
During execution of  `mvn site` the `maven-project-info-reports-plugin` logs the warning:
```Error resolving project artifact: Failure to find org.jboss.arquillian.extension:arquillian-drone-selenium-server:pom:2.5.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project org.jboss.arquillian.extension:arquillian-drone-selenium-server:pom:2.5.0```.

I think issue is that  in `arquillian-drone-bom-2.5.0.pom` file, dependency `arquillian-drone-selenium-server` points to `version 2.5.0`, but that dependency vesion does not exit, at least in maven central repository. Lastest version for `arquillian-drone-selenium-server` is `2.0.1.Final`.

Dependency imported in project as:
  ```
<dependencyManagement>
    <dependencies>
       <dependency>
        <groupId>org.jboss.arquillian.extension</groupId>
        <artifactId>arquillian-drone-bom</artifactId>
        <version>2.5.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by MatousJobanek** [comment]
Hi @konjp 
thanks a lot for reporting this. It was unfortunately forgotten to remove this dependency from the Drone BOM when the subproject was removed.
