### ISSUE TITLE
Firefox instance is started without preferences set via firefoxUserPreferences

### ISSUE THREAD

**Issue by RobertSisaj** [arquillian/arquillian-extension-drone#127]
##### Issue Overview

Firefox instance started with fresh profile does not have applied any user preferences configured via firefoxUserPreferences.

##### Expected Behaviour

Firefox instance started with fresh profile has e.g. "browser.download.folderList" set to value 2 as configured in a file specified in firefoxUserPreferences.

##### Current Behaviour

Firefox instance started with fresh profile has default preferences.

##### Steps To Reproduce
1. In **arquillian.xml** set **firefoxUserPreferences** to point to file with some non default Firefox property, e.g.:
```
user_pref("browser.download.folderList", 2);
```
2. Use Drone to create fresh Firefox instance, manually check **about:config** and the property value.

##### Additional Information

Actually the preferences file is parsed correctly by Drone, but in the end the FirefoxDriverFactory creates the instance using constructor with Capabilities, not FirefoxOptions. This is deprecated since Selenium 3.6.0 and unfortunately the deprecated constructor converts Capabilities to FirefoxOptions with a bug, so anything set in "moz:firefoxOptions" is lost.

Creating FirefoxDriver instance directly using FirefoxOptions passed the preferences correctly as I verified with this simple "patch":
```
$ git diff
diff --git a/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/FirefoxDriverFactory.java b/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/FirefoxDriverFactory.java
index 1913b2c..68ed7ae 100644
--- a/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/FirefoxDriverFactory.java
+++ b/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/FirefoxDriverFactory.java
@@ -72,9 +72,10 @@ public class FirefoxDriverFactory extends AbstractWebDriverFactory<FirefoxDriver
     public FirefoxDriver createInstance(WebDriverConfiguration configuration) {
 
         Capabilities capabilities = getCapabilities(configuration, true);
+        FirefoxOptions options = (FirefoxOptions) capabilities;
 
-        return SecurityActions.newInstance(configuration.getImplementationClass(), new Class<?>[] {Capabilities.class},
-            new Object[] {capabilities}, FirefoxDriver.class);
+        return SecurityActions.newInstance(configuration.getImplementationClass(), new Class<?>[] {FirefoxOptions.class},
+            new Object[] {options}, FirefoxDriver.class);
     }
```

**Comment by MatousJobanek** [comment]
Hi @RobertSisaj 
thx for reporting this issue with a great description and also a proposal for the fix. Next time, don't be afraid/shy and send the fix as a PR, I'll be more than thankful. :-)
