### ISSUE TITLE
Defect in SauceLab extension

### ISSUE THREAD

**Issue by singhravik** [arquillian/arquillian-extension-drone#147]
##### Issue Overview

Defect in SauceLab extension. The logic for extracting username and accessKey extraction from Url seems to be defective. It throws error of 'java.lang.StringIndexOutOfBoundsException: String index out of range: -3' 

##### Expected Behaviour
username and accessKey should get parsed out.

##### Current Behaviour
It throws error of 'java.lang.StringIndexOutOfBoundsException: String index out of range: -3' 

##### Steps To Reproduce
1. Use the below section of configuration in arquillian.xml and use the latest artifact 2.5.1 of extension.
2. Start the test and the extension fails at Line # 104 of extension/arquillian-drone-saucelabs-extension/src/main/java/org/arquillian/drone/saucelabs/extension/webdriver/SauceLabsDriverFactory.java

     username = url.substring(url.lastIndexOf("://") + 3, url.indexOf(":"));

##### Additional Information

Use this configuration :
  <extension qualifier="webdriver">
    <property name="browser">saucelabs</property>
    <property name="username">rsingh_001</property>
    <property name="sauce.connect.binary">/Users/rsing34/Develop/sc</property>
    <property name="url">https://rsingh_001:123456-123456-123456-123456e@ondemand.saucelabs.com:443/wd/hub</property>
    <property name="access.key">123456-123456-123456-123456</property>
    <property name="sauce.connect.managed">true</property>
    <property name="acceptSslCerts">true</property>
    <property name="browserName">chrome</property>
    <property name="platform">macOS 10.13</property>
    <property name="version">69.0</property>
    <property name="seleniumVersion">2.53.0</property>
  </extension>

```

**Comment by singhravik** [comment]
I have a fix. Please create a temp branch so that I can checkin and raise a Pull-Request.

**Comment by bartoszmajsak** [comment]
> I have a fix. Please create a temp branch so that I can checkin and raise a Pull-Request.

@singhravik Thanks for working on this! You can simply fork this repository, push this new branch there and then open Pull Request on GitHub with a single click.

**Comment by singhravik** [comment]
OK, will do.

**Comment by singhravik** [comment]
Refer to PR: https://github.com/arquillian/arquillian-extension-drone/pull/148
