### ISSUE TITLE
Improve XmlStorage mechanism

### ISSUE THREAD

**Issue by jomarko** [arquillian/arquillian-extension-drone#309]
##### Issue Overview

As discussed in PR https://github.com/arquillian/arquillian-extension-drone/pull/308#issuecomment-1005898875, we have an opportunity to improve internal mechanism of driver version detection/validation.

**Comment by jomarko** [comment]
@bartoszmajsak I created this issue, can I somehow assign it to me?

**Comment by bartoszmajsak** [comment]
@jomarko done :)

**Comment by bartoszmajsak** [comment]
I think we should simplify the download logic - see my recent comment on your other PR https://github.com/arquillian/arquillian-extension-drone/pull/308#issuecomment-1007297112

**Comment by bartoszmajsak** [comment]
One more thing btw - if we manage to have similar logic for both Edge and Chrome, meaning we know how to construct URLs to fetch drivers and have URLs for version/os which gives us the version number, there's no reason to call it `XmlStorage`  I believe.

**Comment by bartoszmajsak** [comment]
Fixed in #310
