### ISSUE TITLE
Replace automatic download with WebDriverManager

### ISSUE THREAD

**Issue by jonkoops** [arquillian/arquillian-extension-drone#359]
Instead of rolling a custom implementation to download the correct version of the supported WebDriver we should rely on [WebDriverManager](https://github.com/bonigarcia/webdrivermanager) to do this for us instead.

The reason for this is that our custom implementation actually downloads the wrong version of the drivers by default. This is because it will always fetch the latest version of the driver, instead of one compatible with the version of the browser installed on the system.

WebDriverManager instead will find the correct an compatible binary.

**Comment by jonkoops** [comment]
@bartoszmajsak how would you feel about this functionality? It would allow the Keycloak project to finally move away from PhantomJS, as our CI simply does not work if the correct driver is not retrieved.

**Comment by bartoszmajsak** [comment]
Hi, @jonkoops. I think the less code we have to maintain, the better. There have been some challenges with downloading logic for MS Edge (AFAIR). If that's a popular and vibrant project, we should definitely switch to it.

Would you be willing to give it a try?

**Comment by WolfgangHG** [comment]
Don't blame me if I am completely wrong, but shouldn't the newly introduced Selenium Manager handle this download out of the box? 
https://www.selenium.dev/blog/2023/whats-new-in-selenium-manager-with-selenium-4.11.0/
https://www.lambdatest.com/blog/selenium-manager-in-selenium-4-11-0/

**Comment by lprimak** [comment]
Yes.
