### ISSUE TITLE
Remove support for PhantomJS

### ISSUE THREAD

**Issue by mabartos** [arquillian/arquillian-extension-drone#402]
##### Issue Overview

PhantomJS development is suspended and I believe, it doesn't worth maintaining it for Arquillian Drone.

https://github.com/ariya/phantomjs#phantomjs---scriptable-headless-webkit

**Comment by lprimak** [comment]
I already removed it in the PRs for Graphene I believe

**Comment by jonkoops** [comment]
Should InternetExplorerDriver also be removed? Can log an issue for that if required.

**Comment by mabartos** [comment]
> Should InternetExplorerDriver also be removed? Can log an issue for that if required.

Yes, I'd say so. Please, do it.

**Comment by jonkoops** [comment]
@lprimak which commit resolved this issue?

**Comment by mabartos** [comment]
AFAIK it should be addressed in https://github.com/arquillian/arquillian-extension-drone/commit/ee4ae12fc8435f763e02d3ef9ca2fde1b0c7fac4
