### ISSUE TITLE
Firefox does not work without "browserVersion" property

### ISSUE THREAD

**Issue by WolfgangHG** [arquillian/arquillian-extension-drone#418]
I have an older sample that uses Drone 2.5.2 (and thus Selenium 3.11.0).
Firefox 118.0.1 x64 is installed on my computer.

After upgrading to 3.0.0.Alpha7, there is an error when running the test with "firefox" webdriver - declared in "arquillian.xml" like this (which worked with previous drone version):

```
    <extension qualifier="webdriver">
        <property name="browser">firefox</property>
    </extension>
```

The error message is:
```
java.lang.RuntimeException: 
Unable to instantiate Drone via org.openqa.selenium.firefox.FirefoxDriver(FirefoxOptions): org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Unable to find a matching set of capabilities
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'MYCOMPUTER', ip: '192.168.178.101', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: , moz:debuggerAddress: true, moz:firefoxOptions: {}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: , moz:debuggerAddress: true, moz:firefoxOptions: {}, platformName: ANY}}]
Caused by: org.openqa.selenium.SessionNotCreatedException: 
Could not start a new session. Response code 500. Message: Unable to find a matching set of capabilities
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'MYCOMPUTER', ip: '192.168.178.101', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: , moz:debuggerAddress: true, moz:firefoxOptions: {}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: , moz:debuggerAddress: true, moz:firefoxOptions: {}, platformName: ANY}}]
```

It works when specifying a browser version (at the time of writing this issue, "118.0.1" is currently installed):

    <extension qualifier="webdriver">
        <property name="browser">firefox</property>
        <property name="browserVersion">118</property>
    </extension>

It also works with a wildcard (which is probably a good workaround):
`        <property name="browserVersion">*</property>`

I did not find any documentation on this "browserVersion" syntax.

Is this something that has to changed on the user side when updating to 3.0, or is this some kind of regression?

I can provide a sample if necessary.

**Comment by lprimak** [comment]
3.0 alpha is broken now. We are working to update to newest selenium https://github.com/arquillian/arquillian-extension-drone/pull/401 - for now, 2.x is the only working choice (somewhat, chromedriver downloads are completely broken now)

**Comment by WolfgangHG** [comment]
I noticed the chromedriver issue, too. The chromedriver download location has changed after 114: https://chromedriver.chromium.org/downloads/version-selection

But do you have any idea on whether the "browserVersion" attribute is required now (by Selenium)?

**Comment by lprimak** [comment]
> But do you have any idea on whether the "browserVersion" attribute is required now (by Selenium)?

It is not required by selenium. Drone 3.0-alpha (without the PR) requires it because it's not updated correctly to use Selenium 4.x (which the PR does)

**Comment by WolfgangHG** [comment]
You are right. I picked your pull request, and it works. Closing this issue.
