### ISSUE TITLE
Relative path of firefox binary in arquillian.xml

### ISSUE THREAD

**Issue by SambathKumar** [arquillian/arquillian-extension-drone#42]
Hi,
 Please help me on providing firefox binary loction as relative path in arquillian.xml.

I have given the absolute path of firefox binary location like below and its working fine:

```
<extension qualifier="webdriver">
    <property name="browser">${browser}</property>
    <property name="firefox_binary">C://Users//sampath//AppData//Local//Mozilla_Firefox//firefox.exe</property> 
    <property name="remoteAddress">${selenium.hub.address}</property>
    <property name="remote">${remote}</property>
</extension>
```

I want to give the firefox binary location as relative path like below, but its throwing error ( Firefox binary does not point to a valid executable,  .//Mozilla_Firefox//firefox.exe":)":

```
<extension qualifier="webdriver">
    <property name="browser">${browser}</property>
    <property name="firefox_binary">.//Mozilla_Firefox//firefox.exe</property>
    <property name="remoteAddress">${selenium.hub.address}</property>
    <property name="remote">${remote}</property>
</extension>
```

Thanks and Regards,
M.Sambath Kumar

**Comment by luizfmarins** [comment]
How can I do that with gradle?

**Comment by MatousJobanek** [comment]
This could help: http://stackoverflow.com/questions/24231207/gradle-java-project-replace-single-line-in-file-during-build
