### ISSUE TITLE
why "Drone"?

### ISSUE THREAD

**Issue by Raneves** [arquillian/arquillian-extension-drone#52]
Hi people, why the new name is "Drone"? It is confused.

I'm use version 1.1.5.Final

**Comment by aslakknutsen** [comment]
New since when? Drone has always been Drone.

**Comment by Raneves** [comment]
sorry, why arquillian-extension-DRONE ?

**Comment by aslakknutsen** [comment]
It's within the sci-fi/alien theme of Arquillian; http://aliens.wikia.com/wiki/Arquillian

Drone's are the vesicles Arquillians use to attack the browser bugs. 
http://arquillian.org/images/blog/drone_400.png

If that's what you mean.. ?

**Comment by Raneves** [comment]
Yes. thanks! It is very funny.
I like arquillian and I  using in my company. Arquillian is a amazing  test framework.

**Comment by aslakknutsen** [comment]
Thank you! Glad you find it useful :)
