### ISSUE TITLE
Cannot use chromeOptions in the arquillian.xml

### ISSUE THREAD

**Issue by opichals** [arquillian/arquillian-extension-drone#64]
To configure the drone to provide performance data I need to set chromeOptions capabilities as follows ([complete js webdriver example](http://codegists.com/snippet/javascript/chrome-selenium-timelinejs_axemclion_javascript)):

```
{
    "browserName": "chrome",
    "chromeOptions": {
        "perfLoggingPrefs": {
            "traceCategories": ",blink.console,disabled-by-default-devtools.timeline,benchmark"
        },
        "args": ["--enable-gpu-benchmarking", "--enable-thread-composting"]
    },
    "loggingPrefs": {
        "performance": "ALL"
    }
}
```

It appears that this cannot be easily done in arquillian.xml.

**Comment by opichals** [comment]
https://issues.jboss.org/browse/ARQ-2037

**Comment by MatousJobanek** [comment]
I sent a PR. Please take a look if it works in your case and if it is implemented in a suitable way.
https://github.com/arquillian/arquillian-extension-drone/pull/65
Thanks

**Comment by MatousJobanek** [comment]
Closing this issue as fixed by a1d3e46

**Comment by michalvanco** [comment]
I just tried this change for our use-case and it works perfectly! Thank you @MatousJobanek ;)

**Comment by kvalev** [comment]
It seems that the [documentation](http://arquillian.org/arquillian-extension-drone/#configuring-drone-instances) is out of date, as it does not mention anything about this feature.

**Comment by MatousJobanek** [comment]
@kvalev Thank you for pointing this out - I've added the information about the ChromeOptions only into the release announcement: http://arquillian.org/blog/2016/09/14/arquillian-extension-drone-2-0-1-Final/, but obviously forgot to add to the documentation. I will fix it.

**Comment by MatousJobanek** [comment]
@kvalev fixed http://arquillian.org/arquillian-extension-drone/#chrome-options
thanks again for reporting this
