### ISSUE TITLE
disable drone for the run using maven profile

### ISSUE THREAD

**Issue by punitbisht** [arquillian/arquillian-extension-drone#93]
Hi , 

I am using cukespace https://github.com/cukespace/cukespace to run my features using Arquillian.
there is one issue I am facing with Tags and probably you guys can help me .

I have a suite of features, each features have few tags associated . Now when i use `mvn -PmyProfile clean "-Dcucumber.options=-t @myTag" test` the feature with tag "myTag" executes but other features also launch the browser and close it immediately.

This is expected since the browser is bound to the test which has the driver then. 

is there any way I can disable drone for those tests which are not matching with the tag.

**Comment by MatousJobanek** [comment]
Hi,
thank you for your question. 
Actually, I'm not aware of any possibility to disable Drone in a test. The easiest way is removing the annotation `@Drone`. 
If the tag invokes only some of the test methods and the other ones are ignored, then you can move the WebDriver variable declaration to the test method as its parameter: 
~~~java
@Test
public void yourTest(@Drone  WebDriver browser) {
 ...
}
~~~ 
Then the Drone webdriver instance is created in test method scope and is instantiated only for this specific method. I don't know the implementation of cucumber, so I don't know how they manage skipping of the tests, so it may happen that the Drone instance is created anyway. Please give it a try and let me know if it works.

**Comment by MatousJobanek** [comment]
Lazy initialization is a good idea, but I'm afraid that not easy to do :-/. But if you want to take care of it, I'll be more than happy for any contribution ;-).
On the other hand, having a flag such as `-Darquillian.drone.skip=true` that would skip initialization of the Drone instances would be quite easy to implement. This flag would be checked in `@Before` phase so it would be possible to modify it.
Would that work for you?

**Comment by rmannibucau** [comment]
Hmm, the flag works but thought it was harder to impl than lazy init (which is basically just a kind of proxy) cause the flag requires to set it in a lot of place. But if that's easier for you +1 :), in any case it solves the root issue.

**Comment by punitbisht** [comment]
Thanks @MatousJobanek  @rmannibucau  for considering this feature and making quick changes

**Comment by punitbisht** [comment]
@MatousJobanek is this available with the release??

**Comment by MatousJobanek** [comment]
Yes, forgot to mention it here - it is part of Drone 2.2.0
