### ISSUE TITLE
Multiple instances of chrome.exe on windows 

### ISSUE THREAD

**Issue by punitbisht** [arquillian/arquillian-extension-drone#97]
##### Issue Overview

we are running mvn project on a remote windows machine using jenkins, mvn profile in pom.xml  has below configurations for parallel testing 

```
<forkCount>5</forkCount>
 <reuseForks>false</reuseForks>
```
remote machine is displaying 5 instances of chromedriver and 25 instances of chrome, which is not the case in my MAC OSX. 

<img width="200" alt="screen shot 2017-06-19 at 2 17 23 pm" src="https://user-images.githubusercontent.com/19594631/27302639-7856a9b0-54fd-11e7-80d4-a288d2301fbc.png">

##### Expected Behaviour

5 instances of chromedriver and 5 instances of chrome.

##### Jenkins Details 
Jenkins is running as a service on remote machine

##### Remote Machine Details 

Windows Server 2012 R2 Standard 
##### Additional Information

below are my pom.xml details 
```

<dependencyManagement>

        <dependencies>

            <!-- Arquillian Core dependencies -->
            <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>
                <version>1.1.13.Final</version>
                <type>pom</type>
                <scope>import</scope>
                <exclusions><exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion></exclusions>

            </dependency>
            <!-- Arquillian Drone dependencies and WebDriver/Selenium dependencies -->
            <dependency>
                <groupId>org.jboss.arquillian.extension</groupId>
                <artifactId>arquillian-drone-bom</artifactId>
                <version>2.1.2</version>
                <type>pom</type>
                <scope>import</scope>
                <exclusions><exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion></exclusions>
            </dependency>
            <dependency>
                <groupId>org.arquillian.rusheye</groupId>
                <artifactId>rusheye-impl</artifactId>
                <version>1.0.0</version>
            </dependency>
        </dependencies>

    </dependencyManagement>
    <dependencies>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>21.0</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.graphene</groupId>
            <artifactId>graphene-webdriver</artifactId>
            <version>2.2.1</version>
            <type>pom</type>
            <scope>test</scope>
        </dependency>
         .
         .
        .
 </dependencies>

```

**Comment by MatousJobanek** [comment]
Hi, thank you for reporting this issue.
Unfortunately, currently, we don't have resources to reproduce the issue on the windows machine. 
So, I'd like to ask you a few question to minimize places where the issue could be:
Do you use the automatic download feature? 
Is there any version of Drone it was working with?
Is the problem only with this configuration of windows or does it happen also on other distribution?

**Comment by punitbisht** [comment]
@MatousJobanek This issue has been fixed, I was running Jenkins as a service on remote windows machine . After running as a command , there are just 5 instances of chrome .
